baseurl = "https://serp-secrets.vercel.app/"
title = "SERPsecrets"
languageCode = "en-us"
theme = "mainroad-child"
paginate = 10
enableRobotsTXT = true

[Author]
  name = "Filippo Danesi"
  bio = "I'm a SEO Technical Lead specializing in AI-driven strategies and automation, semantic SEO, web performance... you know, SEO stuff."
  avatar = "img/avatar.png"

[Params]
  description = "Advanced insights and strategies at the nexus of AI and SEO, driving the future of search engine optimization in an AI-driven world."
  opengraph = true
  twitter_cards = false
  readmore = false
  authorbox = true
  pager = true
  post_meta = ["date", "categories"]
  mainSections = ["post", "docs"]
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap"
  lunrIndexOutputFilename = "index.json"

  [Params.logo]
    title = "SERPsecrets"
    subtitle = "Latest SEO News, Strategies, and AI Insights"

  [Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist"]

  [Params.widgets]
    recent_num = 5
    tags_counter = false

  [Params.widgets.social]
    [[Params.widgets.social.custom]]
      title = "LinkedIn"
      url = "https://youtube.com/user/username"
      icon = "linkedin.svg"

  [Params.style.vars]
    highlightColor = "#e22d30"
    fontFamilyPrimary = "'Inter', sans-serif"

  [Params.categoryDescriptions]
    "seo-news" = "Authoritative updates and analyses on SEO developments. Covering algorithm changes, market trends, and emerging practices in digital marketing."
    "seo-strategies" = "In-depth exploration of effective SEO tactics and methodologies. Focusing on keyword research, content optimization, and enhancing user engagement."
    "technical-seo" = "Exploring backend SEO strategies and coding for enhanced site performance and ranking. Insightful coverage on site architecture and technical optimization."
    "artificial-intelligence" = "Examining AI's impact on SEO and digital marketing. Insights into machine learning, algorithmic analysis, and AI-driven optimization strategies."

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1

[outputs]
  home = ["HTML", "RSS", "JSON"]